name: country_guesser
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - requests
    - pandas
    - mapbox-vector-tile
    - fastparquet
    - geopandas
    - tqdm
    - pillow
    - matplotlib
    - astral
    - torch
    - torchvision
    - numpy
    - opencv-python
    - aiohttp
    - asyncio
    - torchmetrics